# Generated by Django 3.2.7 on 2022-08-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование1')),
                ('description', models.TextField(max_length=256, verbose_name='Описание1')),
                ('slug', models.SlugField(default='test', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Категория1',
                'verbose_name_plural': 'Категории1',
            },
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
